services:
  ws:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8888:8888
    volumes:
      - ./server:/app
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./web:/usr/share/nginx/html
