services:
  ws:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8888:8888
  web:
    image: nginx:latest
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 8080:80
