kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dile-ola-ws-ingress
  annotations:
    kubernetes.io/spec.ingressClassName: traefik
#    cert-manager.io/cluster-issuer: letsencrypt-dev
#    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

spec:
  rules:
    - host: ws.dile-ola.disruptiva.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dile-ola-ws-service
                port:
                  number: 80
#  tls:
#    - secretName: dile-ola-ws-tls
#      hosts:
#        - ws.dile-ola.disruptiva.org
